import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map from '../components/Map';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Street Map Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.css" rel="stylesheet" />
      </Head>
      <script async src="https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.js" />

      <main className={styles.main}>
        <Map />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Ali Alhaddad
        </a>
      </footer>
    </div>
  )
}
